#!/bin/bash
set -e

usage() {
    echo "$(basename $0) [--kill] [--help] host container [backup_file]" >&2
    exit 1
}

OPTS=`getopt -o kh --long kill,help -n $(basename $0) -- "$@"`

[[ $? -eq 0 ]] || usage
eval set -- "$OPTS"
kill_connections=false

while true; do
  case "$1" in
    -k | --kill ) kill_connections=true; shift ;;
    -h | --help ) usage; shift ;;
    -- ) shift; break ;;
    * ) break ;;
  esac
done

[[ $# == 2 ]] || [[ $# == 3 ]] || usage

host=${1}
container=${2}
[[ $# == 3 ]] && backup_file="${3}" || backup_file="/dev/stdout"

ssh_command="ssh ${host} -C"
docker_command="sudo docker exec -i ${container}"
psql_command="psql -U postgres postgres"
pg_dumpall_command="pg_dumpall -U postgres"

if ${kill_connections}; then
    ${ssh_command} "${docker_command} ${psql_command} --quiet -c \"SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE pid <> pg_backend_pid();\"" >/dev/null 2>&1
fi

${ssh_command} "${docker_command} ${pg_dumpall_command}|gzip" > ${backup_file}
