#!/bin/bash
set -e

usage() {
    echo "$(basename $0) [--kill] [--help] [--container <id>] host [backup_file]" >&2
    exit 1
}

OPTS=`getopt -o khc: --long kill,help,container: -n $(basename $0) -- "$@"`

[[ $? -eq 0 ]] || usage
eval set -- "$OPTS"
kill_connections=false

while true; do
  case "$1" in
    -k | --kill ) kill_connections=true; shift ;;
    -c | --container ) container=$2; shift; shift ;;
    -h | --help ) usage; shift ;;
    -- ) shift; break ;;
    * ) break ;;
  esac
done

[[ $# == 1 ]] || [[ $# == 2 ]] || usage

host=${1}
[[ $# == 2 ]] && backup_file="${2}" || backup_file="/dev/stdout"

ssh_command="ssh ${host} -C"
psql_command="psql -U postgres postgres"
pg_dumpall_command="pg_dumpall -U postgres"
docker_command=""
if [[ -n "${container}" ]]; then
    docker_command="sudo docker exec -i ${container}"
fi

if ${kill_connections}; then
    ${ssh_command} "${docker_command} ${psql_command} --quiet -c \"SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE pid <> pg_backend_pid();\"" >/dev/null 2>&1
fi

${ssh_command} "${docker_command} ${pg_dumpall_command}|gzip" > ${backup_file}

