#!/bin/bash
set -e

usage() {
    echo "$(basename $0) [--help] [--drop] [--kill] [--host <hostname>] [--container <id>] [backup_file]" >&2
    exit 1
}

OPTS=`getopt -o dkh:c: --long help,drop,kill,host:,container: -n $(basename $0) -- "$@"`

[[ $? -eq 0 ]] || usage
eval set -- "$OPTS"
drop_databases=false
kill_connections=false

while true; do
  case "$1" in
    -c | --container ) container=$2; shift; shift ;;
    -d | --drop ) drop_databases=true; shift ;;
    -h | --host ) host=$2; shift; shift ;;
    -k | --kill ) kill_connections=true; shift ;;
    --help ) usage; shift ;;
    -- ) shift; break ;;
    * ) break ;;
  esac
done

[[ $# -lt 2 ]] || usage
[[ $# == 1 ]] && backup_file="${1}" || backup_file="/dev/stdin"

psql_command="psql -U postgres postgres"
docker_command=""
if [[ -n "${container}" ]]; then
    docker_command="sudo docker exec -i ${container}"
fi
ssh_command=""
if [[ -n "${host}" ]]; then
    ssh_command="ssh ${host} -C"
fi

if [[ -z ${ssh_command} ]]; then
	drop_commands="$(${docker_command} ${psql_command} --tuples-only -c "SELECT 'drop database '||datname||';'FROM pg_database WHERE datistemplate=false and datname != 'postgres';" </dev/null)"
else
	drop_commands="$(${ssh_command} "${docker_command} ${psql_command} --tuples-only -c \"SELECT 'drop database '||datname||';'FROM pg_database WHERE datistemplate=false and datname != 'postgres';\"" </dev/null)"
fi

if ${kill_connections}; then
	if [[ -z ${ssh_command} ]]; then
		${docker_command} ${psql_command} --quiet -c "SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE pid <> pg_backend_pid();" >/dev/null 2>&1 </dev/null
	else
		${ssh_command} "${docker_command} ${psql_command} --quiet -c \"SELECT pg_terminate_backend(pg_stat_activity.pid) FROM pg_stat_activity WHERE pid <> pg_backend_pid();\"" >/dev/null 2>&1 </dev/null
	fi
fi

if ${drop_databases}; then
    while IFS=';' read -ra drop_commands_array; do
        for drop_command in "${drop_commands_array[@]}"; do
            ${ssh_command} "${docker_command} ${psql_command} --quiet -c \"${drop_command}\"" </dev/null
        done
    done <<< "${drop_commands}"
fi
if [[ -z ${ssh_command} ]]; then
	cat ${backup_file} | gunzip -c - | ${docker_command} ${psql_command}
else
	cat ${backup_file} | ${ssh_command} "gunzip -c - | ${docker_command} ${psql_command}"
fi

